/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.TaiKhoan;


public class MainView extends javax.swing.JFrame {

    private TaiKhoan taiKhoan;

    public MainView(TaiKhoan tk) {
        initComponents();
        this.taiKhoan = tk;

        setLocationRelativeTo(null);

        jLabel1.setText("Xin chào: " + tk.getTenDangNhap() +
                        " (" + tk.getVaiTro() + ")");

        phanQuyen();
        initEvent();
    }

    public MainView() {
    initComponents();
    setLocationRelativeTo(null);
}


    // ================== GÁN SỰ KIỆN ======================
    private void initEvent() {

        // MENU
        mnNV.addActionListener(e -> moNhanVien());
        mnKhachHang.addActionListener(e -> moKhachHang());
        mnSanPham.addActionListener(e -> moSanPham());

        mnHoaDon.addActionListener(e -> moHoaDon());
        

        mnDangXuat.addActionListener(e -> dangXuat());
        mnThoat.addActionListener(e -> thoat());

        // TOOLBAR
        btnDangXuat.addActionListener(e -> dangXuat());
        btnSanPham.addActionListener(e -> moSanPham());
        btnThoat.addActionListener(e -> thoat());
        btnHoaDon.addActionListener(e -> moHoaDon());
        
    }

    // ================== CHUYỂN FORM =======================

    private void moSanPham() {
        SanPhamView sp = new SanPhamView();
        new SanPhamController(sp, taiKhoan);
        sp.setVisible(true);
        this.dispose();
    }

    private void moNhanVien() {
        NhanVienView nv = new NhanVienView();
        new NhanVienController(nv, taiKhoan);
        nv.setVisible(true);
        this.dispose();
    }

    private void moKhachHang() {
        KhachHangView kh = new KhachHangView();
        new KhachHangController(kh, taiKhoan);
        kh.setVisible(true);
        this.dispose();
    }

    private void moHoaDon() {
    HoaDonView hd = new HoaDonView(this);  // truyền MainView vào
    hd.setVisible(true);
    this.setVisible(false);
}



    

    // ================== ĐĂNG XUẤT ======================
    private void dangXuat() {
        int chon = javax.swing.JOptionPane.showConfirmDialog(
                this, "Bạn có chắc muốn đăng xuất?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (chon == javax.swing.JOptionPane.YES_OPTION) {

            DangNhapView dn = new DangNhapView();
            new DangNhapController(dn);
            dn.setVisible(true);

            this.dispose();
        }
    }

    // ================== THOÁT CHƯƠNG TRÌNH ======================
    private void thoat() {
        int chon = javax.swing.JOptionPane.showConfirmDialog(
                this, "Bạn có chắc muốn thoát?",
                "Xác nhận",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (chon == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    // ================== PHÂN QUYỀN ======================
    private void phanQuyen() {
        if (taiKhoan == null) return;

        String role = taiKhoan.getVaiTro().trim();

        // Nhân viên không được quản lý nhân viên
        if (!role.equalsIgnoreCase("Admin")
                && !role.equalsIgnoreCase("Quản lý")) {

            mnNV.setVisible(false);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        btnDangXuat = new javax.swing.JButton();
        btnDoanhThu = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnQuanLy = new javax.swing.JMenu();
        mnNV = new javax.swing.JMenuItem();
        mnKhachHang = new javax.swing.JMenuItem();
        mnSanPham = new javax.swing.JMenuItem();
        mnThongKe = new javax.swing.JMenu();
        mnDoanhThu = new javax.swing.JMenuItem();
        mnSL = new javax.swing.JMenuItem();
        mnTonKho = new javax.swing.JMenuItem();
        mnHoaDon = new javax.swing.JMenuItem();
        mnHeThong = new javax.swing.JMenu();
        mnDangXuat = new javax.swing.JMenuItem();
        mnThoat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Xin chào:");

        jToolBar1.setRollover(true);

        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.setFocusable(false);
        btnDangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDangXuat);

        btnDoanhThu.setText("Doanh Thu");
        btnDoanhThu.setFocusable(false);
        btnDoanhThu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDoanhThu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnDoanhThu);

        btnSanPham.setText("Sản Phẩm");
        btnSanPham.setFocusable(false);
        btnSanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnSanPham);

        btnHoaDon.setText("Hóa đơn");
        btnHoaDon.setFocusable(false);
        btnHoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHoaDon);

        btnThoat.setText("Thoát");
        btnThoat.setFocusable(false);
        btnThoat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThoat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnThoat);

        mnQuanLy.setText("QUẢN LÝ");

        mnNV.setText("Nhân Viên");
        mnQuanLy.add(mnNV);

        mnKhachHang.setText("Khách Hàng");
        mnQuanLy.add(mnKhachHang);

        mnSanPham.setText("Sản Phẩm");
        mnQuanLy.add(mnSanPham);

        jMenuBar1.add(mnQuanLy);

        mnThongKe.setText("THỐNG KÊ");

        mnDoanhThu.setText("Doanh Thu");
        mnThongKe.add(mnDoanhThu);

        mnSL.setText("Số Lượng Bán");
        mnThongKe.add(mnSL);

        mnTonKho.setText("Tồn Kho");
        mnThongKe.add(mnTonKho);

        mnHoaDon.setText("Hóa Đơn");
        mnThongKe.add(mnHoaDon);

        jMenuBar1.add(mnThongKe);

        mnHeThong.setText("HỆ THỐNG");

        mnDangXuat.setText("Đăng Xuất");
        mnHeThong.add(mnDangXuat);

        mnThoat.setText("Thoát");
        mnHeThong.add(mnThoat);

        jMenuBar1.add(mnHeThong);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnDoanhThu;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem mnDangXuat;
    private javax.swing.JMenuItem mnDoanhThu;
    private javax.swing.JMenu mnHeThong;
    private javax.swing.JMenuItem mnHoaDon;
    private javax.swing.JMenuItem mnKhachHang;
    private javax.swing.JMenuItem mnNV;
    private javax.swing.JMenu mnQuanLy;
    private javax.swing.JMenuItem mnSL;
    private javax.swing.JMenuItem mnSanPham;
    private javax.swing.JMenuItem mnThoat;
    private javax.swing.JMenu mnThongKe;
    private javax.swing.JMenuItem mnTonKho;
    // End of variables declaration//GEN-END:variables
}
